### PR TITLE
Remove index URL hack

### PR DESCRIPTION
**Pull request by bfirsh**
See also https://github.com/replicate/cog-stable-diffusion/pull/50

### CODE REVIEW

**Comment by zeke** [comment]
Is this depending on anything? or is it ready to go?

**Comment by bfirsh** [comment]
Might be worth testing with some weights if you've got any kicking around -- I have only tested with vanilla stable diffusion.

**Comment by bfirsh** [comment]
Would be neat if we could pass a git sha to the API to try out different templates.

**Comment by zeke** [comment]
> Would be neat if we could pass a git sha to the API to try out different templates.

Good idea

**Pull request closed without merging**
